// ABOUTME: Flat error hierarchy for the LLM client with retryability classification.
// ABOUTME: All errors carry provider context and can be queried for retry eligibility.

/// The primary error type for all LLM client operations.
#[derive(Debug, thiserror::Error)]
pub enum Error {
    #[error("authentication failed for provider {provider}: {message}")]
    Authentication { provider: String, message: String },

    #[error("rate limited by {provider}: retry after {retry_after_ms:?}ms")]
    RateLimited {
        provider: String,
        retry_after_ms: Option<u64>,
    },

    #[error("request to {provider} timed out after {timeout_ms}ms")]
    Timeout { provider: String, timeout_ms: u64 },

    #[error("provider {provider} returned server error (HTTP {status_code}): {message}")]
    ServerError {
        provider: String,
        status_code: u16,
        message: String,
    },

    #[error("invalid request to {provider}: {message}")]
    InvalidRequest { provider: String, message: String },

    #[error("model {model} not found or not available for provider {provider}")]
    ModelNotFound { provider: String, model: String },

    #[error("content filtered by {provider}: {message}")]
    ContentFiltered { provider: String, message: String },

    #[error("context length exceeded for model {model}: {message}")]
    ContextLengthExceeded { model: String, message: String },

    #[error("stream error from {provider}: {message}")]
    StreamError { provider: String, message: String },

    #[error("failed to parse response from {provider}: {message}")]
    ResponseParse { provider: String, message: String },

    #[error("HTTP error communicating with {provider}: {source}")]
    Http {
        provider: String,
        #[source]
        source: reqwest::Error,
    },

    #[error("JSON serialization error: {source}")]
    Serialization {
        #[source]
        source: serde_json::Error,
    },

    #[error("provider {provider} is not configured")]
    ProviderNotConfigured { provider: String },

    #[error("operation cancelled")]
    Cancelled,

    #[error("access denied by {provider} (HTTP 403): {message}")]
    AccessDenied { provider: String, message: String },

    #[error("quota exceeded for {provider}: {message}")]
    QuotaExceeded { provider: String, message: String },

    #[error("network error communicating with {provider}: {message}")]
    NetworkError { provider: String, message: String },

    #[error("operation aborted: {message}")]
    Aborted { message: String },

    #[error("invalid tool call in response from {provider}: {message}")]
    InvalidToolCall { provider: String, message: String },

    #[error("no structured object generated by {provider}: {message}")]
    NoObjectGenerated { provider: String, message: String },

    #[error("configuration error: {message}")]
    ConfigurationError { message: String },

    #[error("{message}")]
    Other { message: String, retryable: bool },
}

impl Error {
    /// Whether this error is safe to retry with the same request.
    pub fn retryable(&self) -> bool {
        match self {
            Error::RateLimited { .. } => true,
            Error::Timeout { .. } => true,
            Error::ServerError { status_code, .. } => {
                matches!(status_code, 500 | 502 | 503 | 529)
            }
            Error::StreamError { .. } => true,
            Error::Http { source, .. } => {
                source.is_timeout() || source.is_connect() || source.is_request()
            }
            Error::NetworkError { .. } => true,
            Error::Other { retryable, .. } => *retryable,
            Error::Authentication { .. }
            | Error::AccessDenied { .. }
            | Error::QuotaExceeded { .. }
            | Error::InvalidRequest { .. }
            | Error::ModelNotFound { .. }
            | Error::ContentFiltered { .. }
            | Error::ContextLengthExceeded { .. }
            | Error::ResponseParse { .. }
            | Error::Serialization { .. }
            | Error::ProviderNotConfigured { .. }
            | Error::InvalidToolCall { .. }
            | Error::NoObjectGenerated { .. }
            | Error::ConfigurationError { .. }
            | Error::Aborted { .. }
            | Error::Cancelled => false,
        }
    }

    /// The provider that originated this error, if applicable.
    pub fn provider(&self) -> Option<&str> {
        match self {
            Error::Authentication { provider, .. }
            | Error::AccessDenied { provider, .. }
            | Error::QuotaExceeded { provider, .. }
            | Error::RateLimited { provider, .. }
            | Error::Timeout { provider, .. }
            | Error::ServerError { provider, .. }
            | Error::InvalidRequest { provider, .. }
            | Error::ModelNotFound { provider, .. }
            | Error::ContentFiltered { provider, .. }
            | Error::NetworkError { provider, .. }
            | Error::InvalidToolCall { provider, .. }
            | Error::NoObjectGenerated { provider, .. }
            | Error::StreamError { provider, .. }
            | Error::ResponseParse { provider, .. }
            | Error::Http { provider, .. }
            | Error::ProviderNotConfigured { provider, .. } => Some(provider),
            Error::ContextLengthExceeded { .. }
            | Error::Serialization { .. }
            | Error::Aborted { .. }
            | Error::ConfigurationError { .. }
            | Error::Cancelled
            | Error::Other { .. } => None,
        }
    }

    /// Suggested retry delay in milliseconds, if the error provides one.
    pub fn retry_after_ms(&self) -> Option<u64> {
        match self {
            Error::RateLimited { retry_after_ms, .. } => *retry_after_ms,
            _ => None,
        }
    }
}

/// Convenience alias for Results using the LLM Error type.
pub type Result<T> = std::result::Result<T, Error>;

/// Classification of an HTTP status code into an error kind.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum StatusClass {
    Success,
    RateLimited,
    Authentication,
    AccessDenied,
    InvalidRequest,
    NotFound,
    ServerError,
    Unknown,
}

impl StatusClass {
    /// Classify an HTTP status code.
    pub fn from_status(code: u16) -> Self {
        match code {
            200..=299 => StatusClass::Success,
            401 => StatusClass::Authentication,
            403 => StatusClass::AccessDenied,
            404 => StatusClass::NotFound,
            422 => StatusClass::InvalidRequest,
            429 => StatusClass::RateLimited,
            400 => StatusClass::InvalidRequest,
            500..=599 => StatusClass::ServerError,
            _ => StatusClass::Unknown,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn rate_limited_is_retryable() {
        let err = Error::RateLimited {
            provider: "anthropic".into(),
            retry_after_ms: Some(1000),
        };
        assert!(err.retryable());
        assert_eq!(err.retry_after_ms(), Some(1000));
        assert_eq!(err.provider(), Some("anthropic"));
    }

    #[test]
    fn timeout_is_retryable() {
        let err = Error::Timeout {
            provider: "openai".into(),
            timeout_ms: 30000,
        };
        assert!(err.retryable());
    }

    #[test]
    fn server_error_retryable_for_specific_codes() {
        for code in [500, 502, 503, 529] {
            let err = Error::ServerError {
                provider: "gemini".into(),
                status_code: code,
                message: "internal".into(),
            };
            assert!(err.retryable(), "HTTP {code} should be retryable");
        }

        let err = Error::ServerError {
            provider: "gemini".into(),
            status_code: 504,
            message: "gateway timeout".into(),
        };
        assert!(!err.retryable(), "HTTP 504 should not be retryable");
    }

    #[test]
    fn auth_errors_not_retryable() {
        let err = Error::Authentication {
            provider: "openai".into(),
            message: "invalid key".into(),
        };
        assert!(!err.retryable());
    }

    #[test]
    fn invalid_request_not_retryable() {
        let err = Error::InvalidRequest {
            provider: "anthropic".into(),
            message: "bad params".into(),
        };
        assert!(!err.retryable());
    }

    #[test]
    fn cancelled_not_retryable() {
        assert!(!Error::Cancelled.retryable());
        assert!(Error::Cancelled.provider().is_none());
    }

    #[test]
    fn other_error_respects_retryable_flag() {
        let retryable = Error::Other {
            message: "transient".into(),
            retryable: true,
        };
        assert!(retryable.retryable());

        let non_retryable = Error::Other {
            message: "permanent".into(),
            retryable: false,
        };
        assert!(!non_retryable.retryable());
    }

    // ── New variant tests ────────────────────────────────────────

    #[test]
    fn access_denied_not_retryable() {
        let err = Error::AccessDenied {
            provider: "openai".into(),
            message: "forbidden resource".into(),
        };
        assert!(!err.retryable());
        assert_eq!(err.provider(), Some("openai"));
    }

    #[test]
    fn access_denied_display() {
        let err = Error::AccessDenied {
            provider: "anthropic".into(),
            message: "org not authorized".into(),
        };
        let msg = err.to_string();
        assert!(msg.contains("access denied"));
        assert!(msg.contains("anthropic"));
        assert!(msg.contains("HTTP 403"));
        assert!(msg.contains("org not authorized"));
    }

    #[test]
    fn quota_exceeded_not_retryable() {
        let err = Error::QuotaExceeded {
            provider: "openai".into(),
            message: "monthly limit reached".into(),
        };
        assert!(!err.retryable());
        assert_eq!(err.provider(), Some("openai"));
    }

    #[test]
    fn quota_exceeded_display() {
        let err = Error::QuotaExceeded {
            provider: "anthropic".into(),
            message: "billing limit".into(),
        };
        let msg = err.to_string();
        assert!(msg.contains("quota exceeded"));
        assert!(msg.contains("anthropic"));
        assert!(msg.contains("billing limit"));
    }

    #[test]
    fn network_error_is_retryable() {
        let err = Error::NetworkError {
            provider: "gemini".into(),
            message: "connection reset".into(),
        };
        assert!(err.retryable());
        assert_eq!(err.provider(), Some("gemini"));
    }

    #[test]
    fn network_error_display() {
        let err = Error::NetworkError {
            provider: "openai".into(),
            message: "DNS resolution failed".into(),
        };
        let msg = err.to_string();
        assert!(msg.contains("network error"));
        assert!(msg.contains("openai"));
        assert!(msg.contains("DNS resolution failed"));
    }

    #[test]
    fn aborted_not_retryable() {
        let err = Error::Aborted {
            message: "user cancelled".into(),
        };
        assert!(!err.retryable());
        assert!(err.provider().is_none());
    }

    #[test]
    fn aborted_display() {
        let err = Error::Aborted {
            message: "user pressed ctrl-c".into(),
        };
        let msg = err.to_string();
        assert!(msg.contains("operation aborted"));
        assert!(msg.contains("user pressed ctrl-c"));
    }

    #[test]
    fn invalid_tool_call_not_retryable() {
        let err = Error::InvalidToolCall {
            provider: "anthropic".into(),
            message: "malformed JSON in tool args".into(),
        };
        assert!(!err.retryable());
        assert_eq!(err.provider(), Some("anthropic"));
    }

    #[test]
    fn invalid_tool_call_display() {
        let err = Error::InvalidToolCall {
            provider: "openai".into(),
            message: "missing required field".into(),
        };
        let msg = err.to_string();
        assert!(msg.contains("invalid tool call"));
        assert!(msg.contains("openai"));
        assert!(msg.contains("missing required field"));
    }

    #[test]
    fn no_object_generated_not_retryable() {
        let err = Error::NoObjectGenerated {
            provider: "gemini".into(),
            message: "model returned text instead of JSON".into(),
        };
        assert!(!err.retryable());
        assert_eq!(err.provider(), Some("gemini"));
    }

    #[test]
    fn no_object_generated_display() {
        let err = Error::NoObjectGenerated {
            provider: "anthropic".into(),
            message: "empty structured output".into(),
        };
        let msg = err.to_string();
        assert!(msg.contains("no structured object"));
        assert!(msg.contains("anthropic"));
        assert!(msg.contains("empty structured output"));
    }

    #[test]
    fn configuration_error_not_retryable() {
        let err = Error::ConfigurationError {
            message: "missing API key".into(),
        };
        assert!(!err.retryable());
        assert!(err.provider().is_none());
    }

    #[test]
    fn configuration_error_display() {
        let err = Error::ConfigurationError {
            message: "invalid base URL".into(),
        };
        let msg = err.to_string();
        assert!(msg.contains("configuration error"));
        assert!(msg.contains("invalid base URL"));
    }

    #[test]
    fn status_class_from_status() {
        assert_eq!(StatusClass::from_status(200), StatusClass::Success);
        assert_eq!(StatusClass::from_status(204), StatusClass::Success);
        assert_eq!(StatusClass::from_status(401), StatusClass::Authentication);
        assert_eq!(StatusClass::from_status(403), StatusClass::AccessDenied);
        assert_eq!(StatusClass::from_status(404), StatusClass::NotFound);
        assert_eq!(StatusClass::from_status(429), StatusClass::RateLimited);
        assert_eq!(StatusClass::from_status(400), StatusClass::InvalidRequest);
        assert_eq!(StatusClass::from_status(422), StatusClass::InvalidRequest);
        assert_eq!(StatusClass::from_status(500), StatusClass::ServerError);
        assert_eq!(StatusClass::from_status(503), StatusClass::ServerError);
        assert_eq!(StatusClass::from_status(301), StatusClass::Unknown);
    }

    #[test]
    fn error_display_messages() {
        let err = Error::RateLimited {
            provider: "anthropic".into(),
            retry_after_ms: Some(5000),
        };
        assert!(err.to_string().contains("anthropic"));
        assert!(err.to_string().contains("5000"));

        let err = Error::ModelNotFound {
            provider: "openai".into(),
            model: "gpt-5-turbo".into(),
        };
        assert!(err.to_string().contains("gpt-5-turbo"));
    }
}
